version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - "./src:/usr/src/app"
    restart: on-failure
    user: 1000:1000
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "8080:80"
    depends_on:
      - php
